Remove qemu stuff
`qemu` 4.0 is required or else the following warnings will be produced:

```
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
```

This isn't really a problem, but it generates a lot of noise. See the following links:

  - https://github.com/RPi-Distro/pi-gen/issues/268
  - https://bugs.launchpad.net/qemu/+bug/1813034

To install `qemu` 4.0 on Ubuntu 18.04 I downloaded and installed the package from https://packages.ubuntu.com/eoan/amd64/qemu-user-static/download.